version: "{build}-{branch}"

init:
  - git config --global core.autocrlf true

build_script:
  - mvn clean package --batch-mode

#test_script:
#  - mvn clean verify --batch-mode

artifacts:
  - path: target\liveman-0.0.1-SNAPSHOT.jar
    name: alice-liveman.jar

cache:
  - C:\Users\appveyor\.m2

deploy:
 - provider: GitHub
   artifact: /.*\.jar/
   draft: false
   prerelease: false
   on:
     branch: master

notifications:
  - provider: Email
    to:
      - orz@myloli.me
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
